### ISSUE TITLE
SAST false positive: CodeQL steps in main workflow not detected

### ISSUE THREAD

**Issue by mjpieters** [ossf/scorecard#1580]
My [current build workflow](https://github.com/mjpieters/SO-userscripts/blob/main/.github/workflows/build.yaml) clearly uses CodeQL steps:

```yaml
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@1a927e9307bc11970b2c679922ebc4d03a5bd980 # v1
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@1a927e9307bc11970b2c679922ebc4d03a5bd980 # v1
```

but this is [not being detected](https://github.com/mjpieters/SO-userscripts/security/code-scanning/14?query=ref%3Arefs%2Fheads%2Fmain):

> ```
> SAST tool detected but not run on all commmits:  
> Warn: 0 commits out of 6 are checked with a SAST tool
> ```

Perhaps the check needs to be updated?

To be explicit: PRs require the CodeQL checks to pass before they can be merged.

Possible cause: I removed the `github/codeql-action/autobuild` action as my repository doesn't require a compilation step.
