### ISSUE TITLE
Feature: clarify meaning of Dangerous Workflow 

### ISSUE THREAD

**Issue by lucasgonze** [ossf/scorecard#2831]
**Is your feature request related to a problem? Please describe.**

I am struggling to figure out the meaning of a flagged problem, and so I can't ameliorate it. Discussion with other programmers skilled in application security failed to yield a clear solution.

The error is:

`Warn: untrusted code checkout '${{ github.event.pull_request.head.ref }}': .github/workflows/reviewdog-workflow.yml:160,
`
The code block is:
```
misspell:
  steps:
    with:
     ref: ${{ github.event.pull_request.head.ref }}
    with:
     github_token: ${{ secrets.github_token }}
```

That has been trimmed for readability. For the full original context, the source code is at https://github.com/magma/magma/blob/master/.github/workflows/reviewdog-workflow.yml

**Describe the solution you'd like**

The documentation at https://github.com/ossf/scorecard/blob/e42af756609b2cde6d757fd45ea05ddf0016ff62/docs/checks.md#dangerous-workflow should be extended so that users can more easily understand the risk and amelioration.

**Describe alternatives you've considered**

The alternative is for users to guess the meaning of the message without being confident in their interpretation.

**Additional context**

https://openssf.slack.com/archives/C0235AR8N2C/p1680729901624789
