### ISSUE TITLE
Feature: Token-Permissions should be more forgiving with permission declarations for single-job workflows

### ISSUE THREAD

**Issue by pnacht** [ossf/scorecard#2927]
**Is your feature request related to a problem? Please describe.**
Scorecard currently penalizes workflows which declare top-level write permissions, but is more forgiving when job-level write permissions are granted.

This makes sense in many cases, but is a bit contradictory when looking at workflows with only a single job.

As a maintainer, it feels weird having to go from

```yml
on: push

permissions:
  contents: write

jobs:
  run_linter:
    # ...
```

to

```yml
on: push

permissions:
  contents: read

jobs:
  run_linter:
    permissions:
      contents: write
    # ...
```

It's more verbose but the actual workflow behavior is identical.

The inverse also applies. If a single-job workflow doesn't declare top-level permissions but does declare job-level permissions (read or write), the lack of top-level permissions should be forgiven.

```yml
on: push

jobs:
  foo:
    permissions:
      contents: read
    # ...

# is behaviorally identical to

on: push

permissions:
  contents: read

jobs:
  foo:
    # ...
```

**Describe the solution you'd like**
Scorecard should score workflows with a single job with declared top-level write permissions as if they were job-level permissions. This follows the same logic of being forgiving of job-level permissions since they indicate the maintainer is aware of what they're doing, they're just declaring the permissions in a slightly wrong place.

Likewise, a single-job workflow that doesn't declare top-level permissions but declares job-level permissions has successfully fully defined the workflow's permissions and should be scored as such.

**Describe alternatives you've considered**
The danger of top-level write permissions is that they are less future-proof. A future contributor could add a second job to the workflow that doesn't need those write permissions. However, this isn't always a reasonable supposition; there are many types of workflows that are unlikely to be expanded with more jobs (i.e. `issue_labeler.yml`, `pr_labeler.yml`, `linter.yml`).

Likewise, a single-job workflow that only declares job-level permissions could grant write-all permissions to a future job.

The best solution would likely be something that adds a slight penalty for the lack of future-proofing (a single-job workflow gets a 9/10 if it uses top-level instead of job-level permissions), but if that requires a more complex intervention, then a "quick fix" of simply giving such workflows a 10/10 seems (imo) better than the status quo.

**Additional context**
This only applies to single-job workflows that declare top-level write permissions (or declare job-level permissions). Workflows that don't declare any top-level permissions should still get a 0/10, since there's no signal that the maintainer knows what they're doing.
