### ISSUE TITLE
BUG: Token-Permissions check not reducing score for job-level `contents: write` permission

### ISSUE THREAD

**Issue by diogoteles08** [ossf/scorecard#2991]
#### Describe the bug
In the scenario of a workflow with read-only top level permissions but `contents: write` as a job-level permissions, no score is being reduced on the Token-Permission check.

#### Reproduction steps
Run the following scorecard evaluation and note that it gets a 10/10 on Token-Permissions.
```
scorecard --repo=diogoteles08/testing-token-permissions --checks=Token-Permissions --commit=e79c59d9c2ab27853fb76389f1203ca3f9832b3a
```
The [code analyzed](https://github.com/diogoteles08/testing-token-permissions/blob/e79c59d9c2ab27853fb76389f1203ca3f9832b3a/.github/workflows/tests-with-top-level-read-all.yml) have this highly vulnerable workflow call:

```
permissions: read-all

jobs:
  third-party-action-with-contents-write:
    runs-on: ubuntu-latest
    name: Call third party action with write permission
    permissions:
      contents: write

    steps:
      - name: "Checkout code"
        uses: not-really-safe-source/arguably-dangerous-action@master
```

This issue occurs in both version 4.10.2 and 4.10.5
#### Expected behavior
The Token-Permission check should detect the permissive `contents: write` permission and the score should have a large reduction.

#### Additional context
I'll assign myself on this issue
