### ISSUE TITLE
BUG: Pinned-Dependencies fails for jobs with complex matrix-defined OS

### ISSUE THREAD

**Issue by pnacht** [ossf/scorecard#3075]
**Describe the bug**
Jobs with matrix-defined OS can cause an internal error in Pinned-Dependencies.

**Reproduction steps**
1. `scorecard --repo apache/beam --checks Pinned-Dependencies --show-details --format json`

```
Error: check runtime error: Pinned-Dependencies: internal error: internal error: unable to determine OS for job: Build python wheels on ${{matrix.arch}} for ${{ matrix.os_python.os }}
```

```json
...
  "checks": [
    {
      "details": null,
      "score": -1,
      "reason": "internal error: internal error: unable to determine OS for job: Build python wheels on ${{matrix.arch}} for ${{ matrix.os_python.os }}",
      "name": "Pinned-Dependencies",
      ...
    }
  ],
...
```

The relevant job is [here](https://github.com/apache/beam/blob/170b597b5eaa56ffd5ac3c97514e4e8be277cb46/.github/workflows/build_wheels.yml#L224-L242) and is defined below. Note that the OS isn't simply a value of the matrix, but a component of a JSON object defined by the matrix:

```yaml
  build_wheels:
    name: Build python wheels on ${{matrix.arch}} for ${{ matrix.os_python.os }}
    needs:
      - check_env_variables
      - build_source
    env:
      CIBW_ARCHS_LINUX: ${{matrix.arch}}
    runs-on: ${{ matrix.os_python.os }}
    strategy:
      matrix:
        os_python: [
          {"os": "ubuntu-latest", "python": "${{ needs.check_env_variables.outputs.py-versions-full }}" },
          {"os": "macos-latest", "python": "${{ needs.check_env_variables.outputs.py-versions-test }}" },
          {"os": "windows-latest", "python": "${{ needs.check_env_variables.outputs.py-versions-test }}" },
        ]
        arch: [auto]
        include:
          - os_python: {"os": "ubuntu-latest", "python": "${{ needs.check_env_variables.outputs.py-versions-test }}" }
            arch: aarch64
    # ...
```

**Expected behavior**
The case should be handled normally (why does Scorecard need to determine the OS?).

If this edge case is too complex to be worth the effort, Scorecard should then ignore failed jobs (with a warning in the details) but run the rest of the Pinned-Dependencies check normally.
