### ISSUE TITLE
BUG: Dangerous-Workflow doesn't trigger on `toJSON(github.event)`

### ISSUE THREAD

**Issue by pnacht** [ossf/scorecard#3554]
**Describe the bug**
The Dangerous-Workflow check currently only triggers when attacker-controlled data is explicitly declared in the workflow.

https://github.com/ossf/scorecard/blob/130a31f/checks/raw/dangerous_workflow.go#L31-L57

However, if the `github.event` object is converted to a JSON object (i.e. for logging) in a `run:` command on a workflow triggered by an external contribution, its contents will contain attacker-controlled data (i.e. the issue/PR title) which can be used for code injection in the workflow.

For example:

```yml
on:
  pull_request_target:

jobs:
  get-pwned:
    runs-on: ubuntu-latest
    steps:
      - name: Log event and get pwned
        run: echo '${{ toJSON(github.event) }}' | jq
```

**Expected behavior**
Dangerous-Workflow should detect this as a dangerous pattern.
