### ISSUE TITLE
[npmCommand] npm install github:package.repo#sha is detected as non pinned dependency

### ISSUE THREAD

**Issue by kuisathaverat** [ossf/scorecard#4589]
**Describe the bug**

The following step in a GitHub workflow is detected as a `Warn: npmCommand not pinned by hash` when it really is pinned.

```yaml
       
      - name: Install Dependencies
        run: |
          npm install github:nodeca/js-yaml#2cef47bebf60da141b78b085f3dea3b5733dcc12
```

**Reproduction steps**
1. Create a workflow like the following
```yaml
name: test
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Dependencies
        run: |
          npm install github:nodeca/js-yaml#2cef47bebf60da141b78b085f3dea3b5733dcc12
```
3. Run the command `scorecard --repo=github.com/owner/repo  --show-details`
4. Check that the new workflow reports the Warning `npmCommand not pinned by hash`

**Expected behavior**

The command is detected as a pinned dependency 

https://docs.npmjs.com/about-packages-and-modules#npm-package-git-url-formats

**Additional context**
